### ISSUE TITLE
service.js in src folder is different from the Service in the bundled versions (resource folder)

### ISSUE THREAD

**Issue by maxnorth** [VividCortex/angular-recaptcha#118]
Looks like these are out of sync. The version of the service being used in the resource folder has an entirely different version of vcRecaptchaService than the one defined in src/service.js, and does not expose the vcRecaptchaServiceProvider described in the documentation.

**Comment by TheSharpieOne** [comment]
It sounds like you are pulling from master, which has had changes made to it since the last release. You should use the [release versions](https://github.com/VividCortex/angular-recaptcha/releases) unless you need something that has not been released (such as the service provider you mention). In the case you need a feature not yet released, you'll have to built a release version locally using grunt.

**Comment by mtrias** [comment]
The release was done. Reopen if this is still an issue.

**Comment by agkunz** [comment]
Having an issue with bower,

`$ bower install angular-recaptcha --save`
```
bower cached        git://github.com/VividCortex/angular-recaptcha.git#3.0.0
bower validate      3.0.0 against git://github.com/VividCortex/angular-recaptcha.git#3.0.0
```

`my bower.json`
```
"angular-recaptcha": "^3.0.0",
```

`your bower.json`
```
"name": "angular-recaptcha",
"version": "2.5.0",
```

Trying to use the service provider, but it's methods don't exist.

**Comment by mtrias** [comment]
Hey @agkunz,

Thanks for reporting this.

I think i fixed it. Could you please try again and let me know?

**Comment by agkunz** [comment]
Tried in my project, didn't see an immediate change.
Tried a blank project
```
$ mkdir test; cd test;
$ npm init; spam enter;
$ bower init; spam enter;
$ bower install angular-recaptcha --save;
```
Still no difference.

**Comment by mtrias** [comment]
That's probably doing it's thing. Could you please try `bower cache clean` ?

**Comment by agkunz** [comment]
Great, I've got the right version now.
Unless you did something else, I'll just assume it took a few minutes for the registry to update.
Thanks for your prompt response!

**Comment by mtrias** [comment]
Awesome! Thank you for bringing this up to us! :beer:

**Comment by agkunz** [comment]
Hey, me again.
Yesterday, I took the new version number at face value.
Coming back to it today, I notice the service provider methods still aren't available.  
The date in the script itself shows `2016-02-18`, which is the same as the 2.5.0 release.
I downloaded the release package and the script is identical.

Am I missing something?

**Comment by mtrias** [comment]
Hey!

I guess master wasn't built then after the last merge. I just built and bumped a patch release. That should fix it.

**Comment by agkunz** [comment]
Cool, appears to be working now.  Thanks again!

**Comment by knigal** [comment]
don't forget to update the download link in README.md, it still points to 3.0.0

**Comment by mtrias** [comment]
Done. Thanks @knigal
