### ISSUE TITLE
ReCAPTCHA couldn't find user-provided function: vcRecaptchaApiLoaded

### ISSUE THREAD

**Issue by abd2561024** [VividCortex/angular-recaptcha#175]
Hi! I have the following message in console `ReCAPTCHA couldn't find user-provided function: vcRecaptchaApiLoaded                 recaptcha__ru.js:367 `. It shows when the ReCAPTCHA widget didn't exist on current page. If I go to my auth page and it loads ReCAPTCHA widget, this message didn't showing in console. 
Any idea how I can solve this a little problem?

**Comment by TheSharpieOne** [comment]
interesting. That must be a new error they are throwing. If reCaptcha is loaded before angular-recaptcha then angular-recaptcha will detect that and just run. If you ensure angular-recaptcha is loaded before recaptcha it will resolve your issue.

**Comment by jrbecart** [comment]
Same error with me:
ReCAPTCHA couldn't find user-provided function: vcRecaptchaApiLoaded  recaptcha__fr.js:305

For info I am using third-party async loader library.
I tried to load angular-recaptcha before recaptcha but it doesn't work.

**Comment by DSpeichert** [comment]
Same here, loading angular-recaptcha before recaptcha doesn't change this.

**Comment by nikhilvm1993** [comment]
same happening for me too..

**Comment by caiojhonny** [comment]
Same here

**Comment by Petya21** [comment]
Including ReCaptcha after angular-recaptcha helped for me.

**Comment by jrbecart** [comment]
Do you think this can be related to [release code out dated (missing lang feature) #173](https://github.com/VividCortex/angular-recaptcha/issues/173) ? Maybe english language is not affected...?

**Comment by alexpchin** [comment]
+1 for this? I'll look into this when I get a moment but if anyone has a solution - please post.

**Comment by kevzlou7979** [comment]
Got the same issue too

**Comment by markfaseldesign** [comment]
I have the same issue.

**Comment by DSpeichert** [comment]
@markfaseldesign I think fix was commited to master in #176 but not released as a version yet.

**Comment by iambrosi** [comment]
@markfaseldesign @DSpeichert This was fixed and released in [v4.0](https://github.com/VividCortex/angular-recaptcha/releases/tag/4.0.0)

**Comment by radianz** [comment]
I updated to the latest version but the issue is still there.

**Comment by bobheath33435** [comment]
I updated to 4.0 and I have the problem too.

**Comment by ryubr** [comment]
I get the master and i have too.. Just 2 days whit any library of captcha for angular and no success.
Thanks for help!!

**Comment by bishtpradeep** [comment]
I'm on 3.0.3 and I was seeing the same message in console but after putting () after the function made it disappear.

<script src="//www.google.com/recaptcha/api.js?onload=vcRecaptchaApiLoaded()&render=explicit"
            async defer>
    </script>
    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/angular-recaptcha/3.0.3/angular-recaptcha.min.js">
    </script>

**Comment by Saidorif** [comment]
I had the same issue "ReCAPTCHA couldn't find user-provided function". I removed document.ready() function. It worked!

**Comment by mne1991** [comment]
I have the same issue, I have no document.ready();

**Comment by Hdezhkam** [comment]
$(document).ready(function() {
      onReCaptchaSuccess =  function onReCaptchaSuccess() {
        console.log('ReCaptcha is done!');
       $('#errorRecapture').hide();
      }
    });

  <div id="recaptchaBox">
                                    <div class="g-recaptcha" data-sitekey="6LdhLgcTAAAAACDeAsmhLLiU2fEyC9iA4hIOiJM9"
                                        data-callback="onReCaptchaSuccess">&nbsp;</div>
                                    <div class="help-block with-errors marg-left-15" id="errorRecapture">&nbsp;</div>
                                </div>
